// Code generated by goctl. DO NOT EDIT.
// Source: wechat.proto

package externalcontactgroupchat

import (
	"context"

	"rpc/wechat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Error                                   = wechat.Error
	ErrorResp                               = wechat.ErrorResp
	ExternalContactWayConclusion            = wechat.ExternalContactWayConclusion
	ExternalContactWayConclusionImage       = wechat.ExternalContactWayConclusionImage
	ExternalContactWayConclusionLink        = wechat.ExternalContactWayConclusionLink
	ExternalContactWayConclusionMiniprogram = wechat.ExternalContactWayConclusionMiniprogram
	ExternalContactWayConclusionText        = wechat.ExternalContactWayConclusionText
	ExternalContactWayData                  = wechat.ExternalContactWayData
	ExternalContactWayInfoResp              = wechat.ExternalContactWayInfoResp
	ExternalContactWayListReq               = wechat.ExternalContactWayListReq
	ExternalContactWayListResp              = wechat.ExternalContactWayListResp
	ExternalContactWayReq                   = wechat.ExternalContactWayReq
	ExternalGroupChatInfoReq                = wechat.ExternalGroupChatInfoReq
	ExternalGroupChatListReq                = wechat.ExternalGroupChatListReq
	ExternalUser                            = wechat.ExternalUser
	ExternalUserFollowUser                  = wechat.ExternalUserFollowUser
	ExternalUserFollowUserTag               = wechat.ExternalUserFollowUserTag
	ExternalUserFollowUserWechatChannel     = wechat.ExternalUserFollowUserWechatChannel
	ExternalUserIdReq                       = wechat.ExternalUserIdReq
	ExternalUserIdResp                      = wechat.ExternalUserIdResp
	ExternalUserInfo                        = wechat.ExternalUserInfo
	ExternalUserInfoOpt                     = wechat.ExternalUserInfoOpt
	ExternalUserInfoReq                     = wechat.ExternalUserInfoReq
	ExternalUserInfoResp                    = wechat.ExternalUserInfoResp
	ExternalUserProfile                     = wechat.ExternalUserProfile
	ExternalUserProfileItem                 = wechat.ExternalUserProfileItem
	ExternalUserProfileItemText             = wechat.ExternalUserProfileItemText
	SaveExternalContactWayResp              = wechat.SaveExternalContactWayResp
	UpdateExternalUserRemarkReq             = wechat.UpdateExternalUserRemarkReq
	UseridList                              = wechat.UseridList

	ExternalContactGroupChat interface {
		GetExternalGroupChatInfo(ctx context.Context, in *ExternalGroupChatInfoReq, opts ...grpc.CallOption) (*ErrorResp, error)
		GetExternalGroupChatList(ctx context.Context, in *ExternalGroupChatListReq, opts ...grpc.CallOption) (*ErrorResp, error)
	}

	defaultExternalContactGroupChat struct {
		cli zrpc.Client
	}
)

func NewExternalContactGroupChat(cli zrpc.Client) ExternalContactGroupChat {
	return &defaultExternalContactGroupChat{
		cli: cli,
	}
}

func (m *defaultExternalContactGroupChat) GetExternalGroupChatInfo(ctx context.Context, in *ExternalGroupChatInfoReq, opts ...grpc.CallOption) (*ErrorResp, error) {
	client := wechat.NewExternalContactGroupChatClient(m.cli.Conn())
	return client.GetExternalGroupChatInfo(ctx, in, opts...)
}

func (m *defaultExternalContactGroupChat) GetExternalGroupChatList(ctx context.Context, in *ExternalGroupChatListReq, opts ...grpc.CallOption) (*ErrorResp, error) {
	client := wechat.NewExternalContactGroupChatClient(m.cli.Conn())
	return client.GetExternalGroupChatList(ctx, in, opts...)
}
