// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbExternalUserFollowAttributeFieldNames          = builder.RawFieldNames(&TbExternalUserFollowAttribute{})
	tbExternalUserFollowAttributeRows                = strings.Join(tbExternalUserFollowAttributeFieldNames, ",")
	tbExternalUserFollowAttributeRowsExpectAutoSet   = strings.Join(stringx.Remove(tbExternalUserFollowAttributeFieldNames, "`seq`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbExternalUserFollowAttributeRowsWithPlaceHolder = strings.Join(stringx.Remove(tbExternalUserFollowAttributeFieldNames, "`seq`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tbExternalUserFollowAttributeModel interface {
		Insert(ctx context.Context, data *TbExternalUserFollowAttribute) (sql.Result, error)
		FindOne(ctx context.Context, seq int64) (*TbExternalUserFollowAttribute, error)
		Update(ctx context.Context, data *TbExternalUserFollowAttribute) error
		Delete(ctx context.Context, seq int64) error
	}

	defaultTbExternalUserFollowAttributeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TbExternalUserFollowAttribute struct {
		Seq            int64     `db:"seq"`             // 主键 | 2020-09-10
		ExternalUserid string    `db:"external_userid"` // 外部联系人的userid | 2020-09-10
		Userid         string    `db:"userid"`          // 联系人的userid | 2020-09-10
		Crop           string    `db:"crop"`            // 企微平台(多企微情况) | 2020-09-10
		AttributeType  int64     `db:"attribute_type"`  // 类型 1:备注标签 / 2:视频号信息 | 2020-09-10
		AttributeValue string    `db:"attribute_value"` // 类型值 | 2020-09-10
		Extension      string    `db:"extension"`       // 扩展信息 | 2020-09-10
		Status         int64     `db:"status"`          // 状态 (0:删除,1:正常) | 2020-09-10
		CreatedAt      time.Time `db:"created_at"`      // 创建时间 | 2020-09-10
		UpdatedAt      time.Time `db:"updated_at"`      // 更新时间 | 2020-09-10
	}
)

func newTbExternalUserFollowAttributeModel(conn sqlx.SqlConn) *defaultTbExternalUserFollowAttributeModel {
	return &defaultTbExternalUserFollowAttributeModel{
		conn:  conn,
		table: "`tb_external_user_follow_attribute`",
	}
}

func (m *defaultTbExternalUserFollowAttributeModel) Delete(ctx context.Context, seq int64) error {
	query := fmt.Sprintf("delete from %s where `seq` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, seq)
	return err
}

func (m *defaultTbExternalUserFollowAttributeModel) FindOne(ctx context.Context, seq int64) (*TbExternalUserFollowAttribute, error) {
	query := fmt.Sprintf("select %s from %s where `seq` = ? limit 1", tbExternalUserFollowAttributeRows, m.table)
	var resp TbExternalUserFollowAttribute
	err := m.conn.QueryRowCtx(ctx, &resp, query, seq)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbExternalUserFollowAttributeModel) Insert(ctx context.Context, data *TbExternalUserFollowAttribute) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tbExternalUserFollowAttributeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ExternalUserid, data.Userid, data.Crop, data.AttributeType, data.AttributeValue, data.Extension, data.Status)
	return ret, err
}

func (m *defaultTbExternalUserFollowAttributeModel) Update(ctx context.Context, data *TbExternalUserFollowAttribute) error {
	query := fmt.Sprintf("update %s set %s where `seq` = ?", m.table, tbExternalUserFollowAttributeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ExternalUserid, data.Userid, data.Crop, data.AttributeType, data.AttributeValue, data.Extension, data.Status, data.Seq)
	return err
}

func (m *defaultTbExternalUserFollowAttributeModel) tableName() string {
	return m.table
}
