// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbOperationLogFieldNames          = builder.RawFieldNames(&TbOperationLog{})
	tbOperationLogRows                = strings.Join(tbOperationLogFieldNames, ",")
	tbOperationLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tbOperationLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbOperationLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tbOperationLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbOperationLogIdPrefix = "cache:tbOperationLog:id:"
)

type (
	tbOperationLogModel interface {
		Insert(ctx context.Context, data *TbOperationLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TbOperationLog, error)
		Update(ctx context.Context, data *TbOperationLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTbOperationLogModel struct {
		sqlc.CachedConn
		table string
	}

	TbOperationLog struct {
		Id         int64          `db:"id"`          // 主键 | 柴利瑶 | 2020-05-15
		RelatedId  int64          `db:"related_id"`  // 关联表的id |柴利瑶 | 2020-06-15
		AdminId    int64          `db:"admin_id"`    // 操作人id | 柴利瑶 | 2020-05-15
		Type       int64          `db:"type"`        // 操作类型 | 柴利瑶 | 2020-05-15
		LogDesc    sql.NullString `db:"log_desc"`    // 日志内容 | 柴利瑶 |2020-05-15
		UpdateTime time.Time      `db:"update_time"` // 更新时间
		CreateTime time.Time      `db:"create_time"` // 创建时间
		LogType    int64          `db:"log_type"`    // 日志详情的类型 | 柴利瑶 | 2020-05-15
	}
)

func newTbOperationLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbOperationLogModel {
	return &defaultTbOperationLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_operation_log`",
	}
}

func (m *defaultTbOperationLogModel) Delete(ctx context.Context, id int64) error {
	tbOperationLogIdKey := fmt.Sprintf("%s%v", cacheTbOperationLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbOperationLogIdKey)
	return err
}

func (m *defaultTbOperationLogModel) FindOne(ctx context.Context, id int64) (*TbOperationLog, error) {
	tbOperationLogIdKey := fmt.Sprintf("%s%v", cacheTbOperationLogIdPrefix, id)
	var resp TbOperationLog
	err := m.QueryRowCtx(ctx, &resp, tbOperationLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbOperationLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbOperationLogModel) Insert(ctx context.Context, data *TbOperationLog) (sql.Result, error) {
	tbOperationLogIdKey := fmt.Sprintf("%s%v", cacheTbOperationLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, tbOperationLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RelatedId, data.AdminId, data.Type, data.LogDesc, data.LogType)
	}, tbOperationLogIdKey)
	return ret, err
}

func (m *defaultTbOperationLogModel) Update(ctx context.Context, data *TbOperationLog) error {
	tbOperationLogIdKey := fmt.Sprintf("%s%v", cacheTbOperationLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbOperationLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.RelatedId, data.AdminId, data.Type, data.LogDesc, data.LogType, data.Id)
	}, tbOperationLogIdKey)
	return err
}

func (m *defaultTbOperationLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbOperationLogIdPrefix, primary)
}

func (m *defaultTbOperationLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbOperationLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbOperationLogModel) tableName() string {
	return m.table
}
