// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbUserFieldNames          = builder.RawFieldNames(&TbUser{})
	tbUserRows                = strings.Join(tbUserFieldNames, ",")
	tbUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tbUserFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbUserRowsWithPlaceHolder = strings.Join(stringx.Remove(tbUserFieldNames, "`userid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbUserUseridPrefix = "cache:tbUser:userid:"
)

type (
	tbUserModel interface {
		Insert(ctx context.Context, data *TbUser) (sql.Result, error)
		FindOne(ctx context.Context, userid string) (*TbUser, error)
		Update(ctx context.Context, data *TbUser) error
		Delete(ctx context.Context, userid string) error
	}

	defaultTbUserModel struct {
		sqlc.CachedConn
		table string
	}

	TbUser struct {
		Userid       string    `db:"userid"`         // 员工的userid | 2020-09-10
		Unionid      string    `db:"unionid"`        // 外部联系人在微信开放平台的唯一身份标识（联系人类型是微信用户且企业绑定了微信开发者ID有此字段 第三方应用和代开发应用均不可获取 上游企业不可获取下游企业客户该字段） | 2020-09-10
		Type         uint64    `db:"type"`           // 外部联系人的类型 1:微信用户 / 2:企业微信用户 | 2020-09-10
		Name         string    `db:"name"`           // 外部联系人的名称(微信用户返回其微信昵称 企业微信联系人返回其设置对外展示的别名或实名) | 2020-09-10
		Avatar       string    `db:"avatar"`         // 外部联系人头像(代开发自建应用需要管理员授权才可以获取 第三方不可获取 上游企业不可获取下游企业客户该字段) | 2020-09-10
		Gender       uint64    `db:"gender"`         // 外部联系人性别 0:未知 / 1:男性 / 2:女性(第三方不可获取 上游企业不可获取下游企业客户该字段 返回值为0) | 2020-09-10
		CorpName     string    `db:"corp_name"`      // 外部联系人所在企业的简称(仅当联系人类型是企业微信用户时有此字段) | 2020-09-10
		CorpFullName string    `db:"corp_full_name"` // 外部联系人所在企业的主体名称(仅当联系人类型是企业微信用户时有此字段) | 2020-09-10
		Position     string    `db:"position"`       // 外部联系人的职位(仅当联系人类型是企业微信用户时有此字段) | 2020-09-10
		Status       uint64    `db:"status"`         // 状态 (0:删除,1:正常) | 2020-09-10
		CreatedAt    time.Time `db:"created_at"`     // 创建时间 | 2020-09-10
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间 | 2020-09-10
	}
)

func newTbUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbUserModel {
	return &defaultTbUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_user`",
	}
}

func (m *defaultTbUserModel) Delete(ctx context.Context, userid string) error {
	tbUserUseridKey := fmt.Sprintf("%s%v", cacheTbUserUseridPrefix, userid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `userid` = ?", m.table)
		return conn.ExecCtx(ctx, query, userid)
	}, tbUserUseridKey)
	return err
}

func (m *defaultTbUserModel) FindOne(ctx context.Context, userid string) (*TbUser, error) {
	tbUserUseridKey := fmt.Sprintf("%s%v", cacheTbUserUseridPrefix, userid)
	var resp TbUser
	err := m.QueryRowCtx(ctx, &resp, tbUserUseridKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `userid` = ? limit 1", tbUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbUserModel) Insert(ctx context.Context, data *TbUser) (sql.Result, error) {
	tbUserUseridKey := fmt.Sprintf("%s%v", cacheTbUserUseridPrefix, data.Userid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tbUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Userid, data.Unionid, data.Type, data.Name, data.Avatar, data.Gender, data.CorpName, data.CorpFullName, data.Position, data.Status)
	}, tbUserUseridKey)
	return ret, err
}

func (m *defaultTbUserModel) Update(ctx context.Context, data *TbUser) error {
	tbUserUseridKey := fmt.Sprintf("%s%v", cacheTbUserUseridPrefix, data.Userid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `userid` = ?", m.table, tbUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Unionid, data.Type, data.Name, data.Avatar, data.Gender, data.CorpName, data.CorpFullName, data.Position, data.Status, data.Userid)
	}, tbUserUseridKey)
	return err
}

func (m *defaultTbUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbUserUseridPrefix, primary)
}

func (m *defaultTbUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `userid` = ? limit 1", tbUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbUserModel) tableName() string {
	return m.table
}
