Name: wechat-api
Host: 0.0.0.0
Port: 8080
Mode: dev
MaxConns: 10000
Timeout: 5000 # ms
CpuThreshold: 900 # 降载阈值 默认900(90%) 可允许设置范围0到1000

# 服务配置
DevServer:
  Enabled: true
  Port: 6061 # 开发环境没用容器的话api rpc相同端口会冲突
  HealthPath: "/healthz"
  EnableMetrics: true
  MetricsPath: "/metrics"
  EnablePprof: true

# 是否打印详细日志
Verbose: true
Log:
  ServiceName: wechat-api
  Level: info
  Stat: true
  Compress: false # 是否压缩日志
  StackCooldownMillis: 1000   # 堆栈打印冷却时间
  Mode: file
  Path: ../../deploy/log/api
  KeepDays: 180
  Rotation: daily

# 链路追踪
Telemetry:
  Name: wechat-api
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

# 签名
#Signature:
#  PrivateKeys:
#    - Fingerprint: "xxx"
#      KeyFile: "xxx"
#  Expiry: "1h"
#  Strict: false


WechatRpc:
  Endpoints:
    - 127.0.0.1:9527
  Timeout: 3000
  NonBlock: false  # 是否阻塞模式