// Code generated by goctl. DO NOT EDIT.
// Source: wechat.proto

package externalcontactway

import (
	"context"

	"rpc/wechat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Error                                   = wechat.Error
	ErrorResp                               = wechat.ErrorResp
	ExternalContactWayConclusion            = wechat.ExternalContactWayConclusion
	ExternalContactWayConclusionImage       = wechat.ExternalContactWayConclusionImage
	ExternalContactWayConclusionLink        = wechat.ExternalContactWayConclusionLink
	ExternalContactWayConclusionMiniprogram = wechat.ExternalContactWayConclusionMiniprogram
	ExternalContactWayConclusionText        = wechat.ExternalContactWayConclusionText
	ExternalContactWayData                  = wechat.ExternalContactWayData
	ExternalContactWayInfoResp              = wechat.ExternalContactWayInfoResp
	ExternalContactWayListReq               = wechat.ExternalContactWayListReq
	ExternalContactWayListResp              = wechat.ExternalContactWayListResp
	ExternalContactWayReq                   = wechat.ExternalContactWayReq
	ExternalGroupChatInfoReq                = wechat.ExternalGroupChatInfoReq
	ExternalGroupChatListReq                = wechat.ExternalGroupChatListReq
	ExternalUser                            = wechat.ExternalUser
	ExternalUserFollowUser                  = wechat.ExternalUserFollowUser
	ExternalUserFollowUserTag               = wechat.ExternalUserFollowUserTag
	ExternalUserFollowUserWechatChannel     = wechat.ExternalUserFollowUserWechatChannel
	ExternalUserIdReq                       = wechat.ExternalUserIdReq
	ExternalUserIdResp                      = wechat.ExternalUserIdResp
	ExternalUserInfo                        = wechat.ExternalUserInfo
	ExternalUserInfoOpt                     = wechat.ExternalUserInfoOpt
	ExternalUserInfoReq                     = wechat.ExternalUserInfoReq
	ExternalUserInfoResp                    = wechat.ExternalUserInfoResp
	ExternalUserProfile                     = wechat.ExternalUserProfile
	ExternalUserProfileItem                 = wechat.ExternalUserProfileItem
	ExternalUserProfileItemText             = wechat.ExternalUserProfileItemText
	SaveExternalContactWayResp              = wechat.SaveExternalContactWayResp
	UpdateExternalUserRemarkReq             = wechat.UpdateExternalUserRemarkReq
	UseridList                              = wechat.UseridList

	ExternalContactWay interface {
		CreateExternalContactWay(ctx context.Context, in *ExternalContactWayData, opts ...grpc.CallOption) (*SaveExternalContactWayResp, error)
		UpdateExternalContactWay(ctx context.Context, in *ExternalContactWayData, opts ...grpc.CallOption) (*SaveExternalContactWayResp, error)
		DeleteExternalContactWay(ctx context.Context, in *ExternalContactWayReq, opts ...grpc.CallOption) (*ErrorResp, error)
		GetExternalContactWayInfo(ctx context.Context, in *ExternalContactWayReq, opts ...grpc.CallOption) (*ExternalContactWayInfoResp, error)
		GetExternalContactWayList(ctx context.Context, in *ExternalContactWayListReq, opts ...grpc.CallOption) (*ExternalContactWayListResp, error)
	}

	defaultExternalContactWay struct {
		cli zrpc.Client
	}
)

func NewExternalContactWay(cli zrpc.Client) ExternalContactWay {
	return &defaultExternalContactWay{
		cli: cli,
	}
}

func (m *defaultExternalContactWay) CreateExternalContactWay(ctx context.Context, in *ExternalContactWayData, opts ...grpc.CallOption) (*SaveExternalContactWayResp, error) {
	client := wechat.NewExternalContactWayClient(m.cli.Conn())
	return client.CreateExternalContactWay(ctx, in, opts...)
}

func (m *defaultExternalContactWay) UpdateExternalContactWay(ctx context.Context, in *ExternalContactWayData, opts ...grpc.CallOption) (*SaveExternalContactWayResp, error) {
	client := wechat.NewExternalContactWayClient(m.cli.Conn())
	return client.UpdateExternalContactWay(ctx, in, opts...)
}

func (m *defaultExternalContactWay) DeleteExternalContactWay(ctx context.Context, in *ExternalContactWayReq, opts ...grpc.CallOption) (*ErrorResp, error) {
	client := wechat.NewExternalContactWayClient(m.cli.Conn())
	return client.DeleteExternalContactWay(ctx, in, opts...)
}

func (m *defaultExternalContactWay) GetExternalContactWayInfo(ctx context.Context, in *ExternalContactWayReq, opts ...grpc.CallOption) (*ExternalContactWayInfoResp, error) {
	client := wechat.NewExternalContactWayClient(m.cli.Conn())
	return client.GetExternalContactWayInfo(ctx, in, opts...)
}

func (m *defaultExternalContactWay) GetExternalContactWayList(ctx context.Context, in *ExternalContactWayListReq, opts ...grpc.CallOption) (*ExternalContactWayListResp, error) {
	client := wechat.NewExternalContactWayClient(m.cli.Conn())
	return client.GetExternalContactWayList(ctx, in, opts...)
}
