// Code generated by goctl. DO NOT EDIT.
// Source: wechat.proto

package server

import (
	"context"

	"rpc/internal/logic/externalcontactgroupchat"
	"rpc/internal/svc"
	"rpc/wechat"
)

type ExternalContactGroupChatServer struct {
	svcCtx *svc.ServiceContext
	wechat.UnimplementedExternalContactGroupChatServer
}

func NewExternalContactGroupChatServer(svcCtx *svc.ServiceContext) *ExternalContactGroupChatServer {
	return &ExternalContactGroupChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ExternalContactGroupChatServer) GetExternalGroupChatInfo(ctx context.Context, in *wechat.ExternalGroupChatInfoReq) (*wechat.ErrorResp, error) {
	l := externalcontactgroupchatlogic.NewGetExternalGroupChatInfoLogic(ctx, s.svcCtx)
	return l.GetExternalGroupChatInfo(in)
}

func (s *ExternalContactGroupChatServer) GetExternalGroupChatList(ctx context.Context, in *wechat.ExternalGroupChatListReq) (*wechat.ErrorResp, error) {
	l := externalcontactgroupchatlogic.NewGetExternalGroupChatListLogic(ctx, s.svcCtx)
	return l.GetExternalGroupChatList(in)
}
