// Code generated by goctl. DO NOT EDIT.
// Source: wechat.proto

package server

import (
	"context"

	"rpc/internal/logic/externalcontactway"
	"rpc/internal/svc"
	"rpc/wechat"
)

type ExternalContactWayServer struct {
	svcCtx *svc.ServiceContext
	wechat.UnimplementedExternalContactWayServer
}

func NewExternalContactWayServer(svcCtx *svc.ServiceContext) *ExternalContactWayServer {
	return &ExternalContactWayServer{
		svcCtx: svcCtx,
	}
}

func (s *ExternalContactWayServer) CreateExternalContactWay(ctx context.Context, in *wechat.ExternalContactWayData) (*wechat.SaveExternalContactWayResp, error) {
	l := externalcontactwaylogic.NewCreateExternalContactWayLogic(ctx, s.svcCtx)
	return l.CreateExternalContactWay(in)
}

func (s *ExternalContactWayServer) UpdateExternalContactWay(ctx context.Context, in *wechat.ExternalContactWayData) (*wechat.SaveExternalContactWayResp, error) {
	l := externalcontactwaylogic.NewUpdateExternalContactWayLogic(ctx, s.svcCtx)
	return l.UpdateExternalContactWay(in)
}

func (s *ExternalContactWayServer) DeleteExternalContactWay(ctx context.Context, in *wechat.ExternalContactWayReq) (*wechat.ErrorResp, error) {
	l := externalcontactwaylogic.NewDeleteExternalContactWayLogic(ctx, s.svcCtx)
	return l.DeleteExternalContactWay(in)
}

func (s *ExternalContactWayServer) GetExternalContactWayInfo(ctx context.Context, in *wechat.ExternalContactWayReq) (*wechat.ExternalContactWayInfoResp, error) {
	l := externalcontactwaylogic.NewGetExternalContactWayInfoLogic(ctx, s.svcCtx)
	return l.GetExternalContactWayInfo(in)
}

func (s *ExternalContactWayServer) GetExternalContactWayList(ctx context.Context, in *wechat.ExternalContactWayListReq) (*wechat.ExternalContactWayListResp, error) {
	l := externalcontactwaylogic.NewGetExternalContactWayListLogic(ctx, s.svcCtx)
	return l.GetExternalContactWayList(in)
}
