// Code generated by goctl. DO NOT EDIT.
// Source: wechat.proto

package server

import (
	"context"

	"rpc/internal/logic/externalcontactuser"
	"rpc/internal/svc"
	"rpc/wechat"
)

type ExternalContactUserServer struct {
	svcCtx *svc.ServiceContext
	wechat.UnimplementedExternalContactUserServer
}

func NewExternalContactUserServer(svcCtx *svc.ServiceContext) *ExternalContactUserServer {
	return &ExternalContactUserServer{
		svcCtx: svcCtx,
	}
}

func (s *ExternalContactUserServer) GetExternalUserInfo(ctx context.Context, in *wechat.ExternalUserInfoReq) (*wechat.ExternalUserInfoResp, error) {
	l := externalcontactuserlogic.NewGetExternalUserInfoLogic(ctx, s.svcCtx)
	return l.GetExternalUserInfo(in)
}

func (s *ExternalContactUserServer) GetExternalUserIdByUserId(ctx context.Context, in *wechat.ExternalUserIdReq) (*wechat.ExternalUserIdResp, error) {
	l := externalcontactuserlogic.NewGetExternalUserIdByUserIdLogic(ctx, s.svcCtx)
	return l.GetExternalUserIdByUserId(in)
}

func (s *ExternalContactUserServer) UpdateExternalUserRemark(ctx context.Context, in *wechat.UpdateExternalUserRemarkReq) (*wechat.ErrorResp, error) {
	l := externalcontactuserlogic.NewUpdateExternalUserRemarkLogic(ctx, s.svcCtx)
	return l.UpdateExternalUserRemark(in)
}
