// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package handler

import (
	"net/http"
	"time"

	callback "api/internal/handler/callback"
	externalcontactuser "api/internal/handler/externalcontactuser"
	externalwayqr "api/internal/handler/externalwayqr"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 企微回调处理
				Method:  http.MethodGet,
				Path:    "/",
				Handler: callback.CallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/callback"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 企微外部用户详情
				Method:  http.MethodPost,
				Path:    "/info",
				Handler: externalcontactuser.ExternalUserInfoHandler(serverCtx),
			},
			{
				// 企微外部用户详情列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: externalcontactuser.ExternalUserListHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/externaluser"),
		rest.WithTimeout(2000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 企微联系人二维码添加
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: externalwayqr.ExternalWayQrAddHandler(serverCtx),
			},
			{
				// 企微联系人二维码详情
				Method:  http.MethodPost,
				Path:    "/info",
				Handler: externalwayqr.ExternalWayQrInfoHandler(serverCtx),
			},
			{
				// 企微联系人二维码列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: externalwayqr.ExternalWayQrListHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/externalwayqr"),
		rest.WithTimeout(2000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
