// Code generated by goctl. DO NOT EDIT.
package types

type CallbackReq struct {
	ToUserName string      `json:"ToUserName"`
	CreateTime int         `json:"CreateTime"`
	MsgType    string      `json:"MsgType"`
	Event      string      `json:"Event"`
	ChangeType string      `json:"ChangeType"`
	Data       interface{} `json:"Data"`
}

type ExternalUserRequest struct {
	ExternalUseridList []string `json:"external_userid_list,optional"`
	UnionidList        []string `json:"unionid_list,optional"`
}

type Request struct {
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
